-- MySQL Script generated by MySQL Workbench
-- 10/31/17 11:11:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario` DEFAULT CHARACTER SET utf8 ;
USE `inventario` ;

-- -----------------------------------------------------
-- Table `inventario`.`clasificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`clasificaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`dependencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`dependencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`proyectos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`articulos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `numeroemco` VARCHAR(45) NULL,
  `serie` VARCHAR(100) NULL,
  `factura` INT NULL,
  `clasificaciones_id` INT NOT NULL,
  `dependencias_id` INT NOT NULL,
  `prestamo` TINYINT(1) NULL DEFAULT 0,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `proyectos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_articulos_clasificaciones_idx` (`clasificaciones_id` ASC),
  INDEX `fk_articulos_dependencias1_idx` (`dependencias_id` ASC),
  INDEX `fk_articulos_proyectos1_idx` (`proyectos_id` ASC),
  CONSTRAINT `fk_articulos_clasificaciones`
    FOREIGN KEY (`clasificaciones_id`)
    REFERENCES `inventario`.`clasificaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_dependencias1`
    FOREIGN KEY (`dependencias_id`)
    REFERENCES `inventario`.`dependencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_proyectos1`
    FOREIGN KEY (`proyectos_id`)
    REFERENCES `inventario`.`proyectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(16) NOT NULL,
  `nombre` VARCHAR(16) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `perfil` ENUM('Administrador', 'Usuario') NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `inventario`.`historicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`historicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `articulos_id` INT NOT NULL,
  `dependencias_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `tipo` ENUM('Pase', 'Prestamo', 'Alta', 'Retorno', 'Reparacion') NOT NULL,
  `observacion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historicos_articulos1_idx` (`articulos_id` ASC),
  INDEX `fk_historicos_pases_dependencias1_idx` (`dependencias_id` ASC),
  INDEX `fk_historico_pases_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_historicos_articulos1`
    FOREIGN KEY (`articulos_id`)
    REFERENCES `inventario`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historicos_pases_dependencias1`
    FOREIGN KEY (`dependencias_id`)
    REFERENCES `inventario`.`dependencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_pases_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `inventario`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
